name: push_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_core: ^2.7.1
  firebase_messaging: ^14.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  go_router: ^6.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
